### ISSUE TITLE
Opacity when not using names

### ISSUE THREAD

**Issue by Kedyn** [Kedyn/fusliez-notes#10]
Opacity should be removed when not using player names.

**Comment by francistse23** [comment]
not sure what you meant by that. can you elaborate?

**Comment by Kedyn** [comment]
If you go into the controls and uncheck "Show players name[s]", typo, then names are not used, but if the player does not have a name it's opacity is 0.6 and it should be fully visible because no names are being used, the opacity is more to indicate the user that the player does not have a name.
