### ISSUE TITLE
Czech Translation For The Page

### ISSUE THREAD

**Issue by FrederikPos** [Kedyn/fusliez-notes#105]
I didn't know to make an issue or pull request so I made this basically I wanted to make Czech translations for the page because it's actually my first language and I wanted it because my friends who don't know too much about English wanted to use this but couldn't because they don't know that much English only the basic sentences if anyone knows how to help to get the translation on the page please comment thank you.

**Comment by Kedyn** [comment]
First of all, thank you for your interest in doing this. The translations file are locate in the `src/assets/locale/` folder. You can just copy the `en-US/translation.json` file and create a folder called `cs-CZ` with your own `translation.json` file in it. I would also like to note that we are working on the new release for the project, which contains a bit more things that need translation, so if you would like to wait until then to make them I will comment on this issue as soon as we get close to releasing.

**Comment by frederik69420** [comment]
I will wait until the new update and thank you for telling me what to do when the update happens.

**Comment by Kedyn** [comment]
I think that is all the new things we will adding for the next version, if you still willing to do the translation please do so.
