### ISSUE TITLE
Wins/Losses Displaying NaN

### ISSUE THREAD

**Issue by francistse23** [Kedyn/fusliez-notes#108]
The progress bars will show `NaN` W/L if the input is input for the corresponding field is empty

![image](https://user-images.githubusercontent.com/38173305/98433526-bb93ef00-207c-11eb-89d6-00359da98b4c.png)

**Comment by Kedyn** [comment]
Already fixed https://github.com/Kedyn/fusliez-notes/commit/fdcc3715f681ee21fb53e2d6a4ce0c56e4b08d98

**Comment by francistse23** [comment]
my bad, didnt see it
