### ISSUE TITLE
Show player's name in the map section

### ISSUE THREAD

**Issue by Coleyra** [Kedyn/fusliez-notes#112]
I'm colorblind and i'm mixing up the white / cyan, and blue / purple colors of the players.
It would help a lot if we could have the player's name showed above the player's miniature in the map section.

**Comment by dauthleikr** [comment]
I'd love this

**Comment by francistse23** [comment]
@Kedyn if you or anyone else on the team isn't against this, I'm open to start tackling the issue

**Comment by francistse23** [comment]
resolved in PR #123
