### ISSUE TITLE
Add second timer

### ISSUE THREAD

**Issue by Hiosdra** [Kedyn/fusliez-notes#121]
Hi, I think it would be a great idea to add some kind of timer for people who know how long each task have to be done, but don't have great ability to count time in the brain. I did it for myself by adding iframe to some website with just seconds part of timer in place of notes and I think it's very useful. But sadly I don't have knowledge about frontend to do it better :/

**Comment by francistse23** [comment]
hey Hiosdra, thanks for the suggestion

the dev team will discuss on the possibility to implement some sort of timer if it aligns with the team's goals and vision
