### ISSUE TITLE
Update languages

### ISSUE THREAD

**Issue by Kedyn** [Kedyn/fusliez-notes#124]
- [x]  en-US
- [x]  es-MX ( @eduardovegar )
- [x]  de-DE ( @Fabian9799 )
- [x]  fa-IR ( @parsaaes )
- [x]  fr-FR ( @Coleyra )
- [x]  pl-PL ( Michał Stankiewicz)
- [ ]  pt-BR ( @danilolmoura )
- [x] ru-RU ( @Kinishina )
- [x] cs-CZ ( @Drison64 )
- [x] he-IL ( Itay Kabalo )
- [x] mg-MG ( @Unviray )
- [x] pt-PT ( Nuno )
- [ ] nl-NL ( @pboschma )

**Comment by Fabian9799** [comment]
Added de-DE Translation #127

**Comment by Drison64** [comment]
Added cs-CZ translation #110

**Comment by Kedyn** [comment]
@Drison64 would you mind also adding yourself to the readme file if you have not done so, thank you.

**Comment by Drison64** [comment]
Hey, sure. I have created a PR for it, #128 . Thank you!

**Comment by eduardovegar** [comment]
Working on the es-MX translation !

**Comment by Unviray** [comment]
Hi, I really like your project. Can I contribute to add Malagasy language (`mg-MG`) ?

**Comment by Kedyn** [comment]
Sure, contributions are more than welcome.

**Comment by Coleyra** [comment]
Updated fr-FR translation #109

**Comment by Unviray** [comment]
Added mg-MG translation #130

**Comment by eduardovegar** [comment]
Updated es-MX translation #131
