### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by Kedyn** [Kedyn/fusliez-notes#13]
As mention on issue #5 we might want to follow the following structure:

```
./ComponentName/                       The folder containing the component
  ComponentName.styles.ts           The file containing the components styles
  ComponentName.tsx                   The actual component
  index.ts                                         File that exports the component so imports can just be /components/ComponentName/ instead of /component/ComponentName/ComponentName
```

There is a VSCode extension that generates this files called **VSCode React Component Generator**.

I also have a few snippets I could put in the repo so we can all follow the same/similar format.

- [x] Main content (score /players section)
- [x] Controls content ( Score buttons, reset button / notes)
- [x] Map content

**Comment by francistse23** [comment]
I'm down if it's easier to manage component and styles that way. If we are following that format, either have a template or you can start converting one of the components? That way, whoever else want to contribute can use that as a reference.

Not sure about moving away from react strap. It could work, but it'll be a lot of work to restructure everything

**Comment by francistse23** [comment]
If we are moving away from react strap, I have heard good things about emotion and tailwind. And styled-components of course

**Comment by chilblane** [comment]
You will still need to find a solution for global css. I usually prefer to keep my css (as sass files) separate from the javascript, and I have extensive experience doing so in React projects. I think this project should not be large enough to justify sass preprocessing OR something as complex as tailwind.

But again, global css is still an issue. I would also really suggest looking into using css variables, especially for how helpful they are with theming.

**Comment by francistse23** [comment]
yeah personally, I only have experience doing smaller projects and managed to get away with not-so-great structure that allowed reusing some variables for conditional rendering. not much with global css/css variable though

**Comment by chilblane** [comment]
If you do go the centralized scss route, I can help. While this is a Hugo blog, I pretty much used the same organization for several React projects at work. It might give you some ideas. https://github.com/chilblane/chilblane-blog/tree/master/themes/chilblane/assets/sass

**Comment by francistse23** [comment]
sounds great. I'll leave it to Kedyn to make that decision though. only contributing/helping with the smaller things ;)

**Comment by Kedyn** [comment]
That is a cool structure @chilblane maybe we could just do that... this is what I had in mind:

https://github.com/Kedyn/fusliez-notes/tree/restructure

as u can see in the components section, each component has its folder with the actual component and it's styles. My current version utilizes jss, but we can easily just change it to be css or scss in that format.

PS: I added an example on the .vscode folder along with some snippets.

**Comment by chilblane** [comment]
Yeah usually I would keep the component styles together with their matching jsx/tsx.

I see also you put the "global" styles in themes folder, which is fine I suppose.
