### ISSUE TITLE
Reset everything not working

### ISSUE THREAD

**Issue by actvise** [Kedyn/fusliez-notes#133]
Hello!
Today i noticed that the reset everything button isnt working.

Is there a solution for that?

**Comment by Kedyn** [comment]
Could you be more specific please. Do you mean it does not reset the map section? If so, that was done intentionally, but it will be added on the next version. If you mean that it does not reset the score or the map sections, that is a problem, but I have tested it on my end and it works as intended. Thank you for reporting.

**Comment by actvise** [comment]
If i click on the "Reset" Button it doesnt do anything. it only resets if you reload the page.

**Comment by francistse23** [comment]
hey actvise, as Kedyn mentioned in his previous comment, the reset function on the app is working as intended (tested it on my end as well).

so far we haven't received any other bug reports about this specific issue you are having.

if you can provide a screen capture or some sort showing us the bug, it'll be easier for us to pinpoint the issue

additionally, please check if you are accessing the app through the correct link. I know others have forked the project and might have published their own version with the legacy code. [kedyn.github.io/fusliez-notes/](current version)

thanks

**Comment by actvise** [comment]
Nevermind the issue is fixed.
