### ISSUE TITLE
Unused Players shouldn't show in the list to drag to the map

### ISSUE THREAD

**Issue by Anusien** [Kedyn/fusliez-notes#139]
It would be nice if colors that are in the unused section don't show up to drag onto the map. One of the powerful things about the map is that as you drag players onto the map, you can see who's left behind. This is sort of muddled because even when everyone is accounted for, you still have two extra meeples behind (plus dead people).

Like #117, this would require having specific meanings to certain sections. Not sure if that conflicts with your plans. You might be able to accomplish something similar just by only including colors who have a name assigned.

**Comment by Kedyn** [comment]
Thank you for your input. It is currently in progress. #123
