### ISSUE TITLE
More themes, including streamer themes

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#14]
Low priority enhancement:

In addition to the generic light and dark themes, more themes can be added, specifically themes for streamers. Example: a Fuslie theme that matches up cleanly with the rest of her stream design and branding.

These additional themes can be accessed from a dropdown instead of the toggle. Potentially, depending on if it's a problem, the streamer themes would not be able to be picked and instead accessed from unique urls for the streamer.

**Comment by Kedyn** [comment]
We are currently re-structuring the project this includes an update on the ability to add more themes so should be coming on an upcoming patch
