### ISSUE TITLE
The players on the map looks big in mobile devices

### ISSUE THREAD

**Issue by ambu-LANCE** [Kedyn/fusliez-notes#148]
![Screenshot_20210121-102928_Chrome](https://user-images.githubusercontent.com/74086825/105282666-dcc4a000-5bd4-11eb-8008-ccce5f8ff073.jpg)

**Comment by francistse23** [comment]
hey, thanks for reporting the potential bug.

if possible, can you share the device/browser you're seeing the issue in? and provide a gif of you navigating to that page so we can see the bug in real time.

many thanks

**Comment by Kedyn** [comment]
Should not be relevant on the next version.
