### ISSUE TITLE
Dead body glitch

### ISSUE THREAD

**Issue by wesley61** [Kedyn/fusliez-notes#149]
There has been a bug that makes the dead bodies move after they are marked dead. If you put an among us character on the map and mark it dead, it will move, and sometimes off the map. This is very annoying because you have to move the characters back to the correct place again. It sometimes duplicates an undraggable version of the character, and if you move the original one, the clone will start moving with it. But, the dead bodies has actually been malfunctioning, because of the clone of among us characters (involves dead bodies), and sometimes, the bodies merge with each other. The characters keep on moving, making it hard to really keep track.

DEAD BODY GOING OFF THE MAP:
<img width="360" alt="Screenshot 2021-01-22 at 3 48 02 PM" src="https://user-images.githubusercontent.com/71319668/105462218-46be7180-5cc9-11eb-924f-85c3b8f24d26.png">

It shouldn't do this, and I really want this bug to be fixed. To activate this, simply put 2 players on the corner of the map. Then double click them. This should activate the "moving without dragging" glitch. Put the characters on the corner again if they have still not gone through the map. Double click them and they should go out of the boundaries.

**Comment by Kedyn** [comment]
I am unable to replicate this issue, would you mind telling me the name of the browser you are using.

**Comment by ToxicToast** [comment]
@Kedyn its on every Browser as long as you open the Console or Resize the Window

**Comment by Kedyn** [comment]
@ToxicToast , I have tested it multiple times, I do not get the same bug, but I have seen a position movement when opening the console or resizing.

**Comment by Kedyn** [comment]
Should be fixed and it will be  reflected on the next release.
