### ISSUE TITLE
Mobile-friendly app

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#15]
For non-stream users of the app, the case can be argued that this app could be great on a mobile web browser if a user wants to "take notes" on their phone. We should look into how to make a great experience for mobile devices where the viewport is <500px wide.

**Comment by Kedyn** [comment]
Yes, I do think we want to keep non-streamer users to have an option to use mobiles so maybe after everything is working great on desktop we can fix the mobile experience.
