### ISSUE TITLE
The crew mate icon is now very small.

### ISSUE THREAD

**Issue by nobu02** [Kedyn/fusliez-notes#156]
First of all, thank you for continuing to support a very useful tool.

With this update, the crew mate icon is now very small.
I want the size to be selectable.
Also, the previous drag-drop placement was convenient.
I want it to be selectable.

**Comment by Kedyn** [comment]
The problem with making them bigger is that they will be even bigger when zooming in.
As for the drag and drop, you can still drag characters around once you place a character into the map.

**Comment by nobu02** [comment]
I personally liked the size of the map and character icon before the update.
So I think it would be great if you could choose between the current style and the current style.

**Comment by Anusien** [comment]
Is it intentional that crewmate icons no longer show the player name?

**Comment by Kedyn** [comment]
Yes, I mostly released this "incomplete" version just to add the map, but many of the features we used to have still need to be added.

**Comment by nobu02** [comment]
I know it's hard, but good luck!
Personally, the previous format is better than this one.
Because it was easy to see who wasn't set visually.

**Comment by Kedyn** [comment]
I have added an option in the settings that will allow you to set the scale factor for the map player characters, I find that around 2  or 3 (maybe 2.5) is around the same size as the old version. I would much appreciate it if anyone can test this and tell me their thoughts. You can view this upcoming change at https://kedyn.github.io/fusliez-notes/next/ . Please note that using the next version might break some of the current stable version page, so I recommend using a private or incognito session.

As for having the twelve characters already on the map I think adding an option to add this at the bottom of each map, in the meantime, one could add this twelve manually as moving the characters in the sections will also be reflected on the map.

**Comment by nobu02** [comment]
@Kedyn 
Thank you for the quick reflection.
I checked it immediately.
The character size is ideal.

When the same color is placed on the map, can't the first placed character move?
Or there should be an option to prevent the same color from being placed.
Thank you for your response!

**Comment by Kedyn** [comment]
First, thank you for your feedback on the newly added scaling option.

I feel as that could be better addressed in another/new issue. I will not be adding anything other than the two "features" I mentioned previously. One: the option to resize map characters and two: the option to start with the twelve characters already placed on the map.

**Comment by nobu02** [comment]
@Kedyn 
Thank you for the quick reflection.
I also checked the initial installation option for the character icon. Very good.

The camera position on the air-ship map is incorrect, so you should use a modified map.
I have another request.
I like the previous aspect ratio of the map scale.
If you don't close the left side, you won't be able to see it horizontally and it will be a little difficult to see.
