### ISSUE TITLE
Include version and release date somewhere visible on the app

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#16]
Just for reference purposes. It can be super small or behind a toggle.

**Comment by Kedyn** [comment]
I think we can put this on a modal dialog that opens with a about button, in it we can also add things like the features available to the users and things of that nature.

**Comment by Kedyn** [comment]
Also, was not good at keeping track of the patches since it was just minor things I was changing but according to your fork on codesandbox it was version 3 so maybe next version we can call it vesion 4.0.0 and then start patching stuff from there...

What do you think?

**Comment by chilblane** [comment]
imo i'd say we're not at a full 1.0 yet

**Comment by Kedyn** [comment]
yeah.. i usually start at 0.1.0 so all those version were more like 0.2.0 0.3.0 ... so any suggestion for the name of the next version?

**Comment by chilblane** [comment]
whatever seems good, i guess.
