### ISSUE TITLE
Track Emergency Button Usage

### ISSUE THREAD

**Issue by tokkiyaa** [Kedyn/fusliez-notes#163]
**Is your feature request related to a problem? Please describe.**

I always forget who used the Emergency Button. 
It would be great if fusliez-notes provides Emergency Button usage tracking feature.

**Describe the solution you'd like**

add Emergency Button tracker in the SlideDrawer

**Describe alternatives you've considered**

write in notepad each time Emergency Button is used.

cons of this solution
- require keyboard typing
- hard to recognize how many buttons are left

**Additional context**
N/A

**Comment by tokkiyaa** [comment]
checked this issue is accepted.
I will work on this issue.

**Comment by Kedyn** [comment]
Sorry I mislabeled it, meant to put it available. Accepted means someone is working on it, but since you are working on it, it is now Accepted. Looking forward to what you will do with it.

**Comment by tokkiyaa** [comment]
I will start fixing this issue this week!

**Comment by tokkiyaa** [comment]
still wip

**Comment by tokkiyaa** [comment]
almost done

**Comment by LS-NONCE** [comment]
Huh

Pada tanggal Kam, 1 Jul 2021 14.02, Kedyn Macedonio <
***@***.***> menulis:
