### ISSUE TITLE
Fix the aspect ratio of the map.

### ISSUE THREAD

**Issue by nobu02** [Kedyn/fusliez-notes#167]
Fix the aspect ratio of the map.
The aspect ratio of the map varies with maximization or browser size. This makes the map hard to see.

Also, the position of the air-ship camera is wrong, so please use the corrected map.

**Comment by Kedyn** [comment]
I am actually reworking the map section because it lags when zooming into it. I am sorry I have not had time to update my to-do list on the Project section of this repo. The map is already fixed, just waiting to finish the map section rework to finally push v1.0.0. Thank you for reporting this!

**Comment by nobu02** [comment]
Thank you for your reply!
I use it frequently with a useful tool.
I am looking forward to the release of the official version.
