### ISSUE TITLE
Skeld room names in wrong place

### ISSUE THREAD

**Issue by Anusien** [Kedyn/fusliez-notes#171]
**Describe the bug**
When I look at the Skeld map, the text for the rooms is misplaced; basically none of them are near the actual room. This only happens on Skeld and it even happens in incognitio mode.

**To Reproduce**

1. Open the app
2. Select Skeld

**Expected behavior**
The names of the rooms are located in the room.

**Screenshots**
![Skeld Text](https://user-images.githubusercontent.com/1687436/122092861-0a062a80-cdd0-11eb-9308-8a7b7012d6d7.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser Chrome
- Version 90.0.4430.212 (Official Build) (64-bit)
- Also happens in Version 91.0.4472.77 (Official Build) beta (64-bit)

**Application version**

v1.0.0-beta.2

**Comment by Kedyn** [comment]
First of all, thank you for taking the time in reporting this issue. This has already been addressed, upcoming changes can be viewed: https://kedyn.github.io/fusliez-notes/next/

**Comment by Anusien** [comment]
Verified fixed in the "next" update.
