### ISSUE TITLE
Don't require all the maps for initial startup

### ISSUE THREAD

**Issue by Anusien** [Kedyn/fusliez-notes#172]
**Is your feature request related to a problem? Please describe.**
When first launching the application, it took 20 seconds to download all the maps and things. This is very frustrating to me, and it's not clear that it's even working. This was very frustrating to me. It will probably get worse in the future as Among Us adds new maps (5th one coming today or soon)!

**Describe the solution you'd like**
Don't block the application startup on the maps. Instead show the selector, and download the maps then. (Maybe you can also download the other maps in the background).

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by Kedyn** [comment]
Thank you for your report, I will take a look at this. I thought I had addressed this before, but most of gotten lost.
