### ISSUE TITLE
Don't have separate images for the map, cameras, and vents

### ISSUE THREAD

**Issue by Anusien** [Kedyn/fusliez-notes#173]
**Is your feature request related to a problem? Please describe.**
The app needs to download a lot of stuff to run for the first time. And until it's all downloaded, it won't work at all. This has been frustrating to me where it's not clear if it's broken or not, and I don't know if it will work.

**Describe the solution you'd like**
It seems like a lot of the slowness in loading the app for the first time is that the browser can only make a few simultaneous requests from the https://kedyn.github.io/ domain at a time. So even though the cameras and vents are comparatively small images, they can take a long time to download.

If the map image contained the cameras and vents on it in a single image, I think it would download much quicker.

**Describe alternatives you've considered**
The images for the vents and cameras are pretty huge (hundreds of kB) for comparatively simple images). If you made them SVGs instead, I suspect it would get the file sizes way down.

Also, the Polus images are only 100kB instead of the 400+ of the other maps. Was there some kind of mechanism you used to generate those that could shrink the others?

If you're not using a CDN to serve these images, that might be a big help. It takes 10+ seconds to download some of the images; they're not *that* big.

**Additional context**

**Comment by Kedyn** [comment]
Thank you for your input, I had a few ideas such as allowing not to hide both of those things, but as I do not count with much time as I would like... I will be combining the images.
