### ISSUE TITLE
Toggle to disable scroll wheel or drag on the map

### ISSUE THREAD

**Issue by Anusien** [Kedyn/fusliez-notes#174]
**Is your feature request related to a problem? Please describe.**
I often accidentally mess up the map. I'll hit the scroll wheel and accidentally zoom it, or I'll try to move a bean and accidentally drag it. This is frustrating because it's hard to get back exactly right. But I sometimes end up with beans off-screen, meaning I can't find them when I try to put them on the map (or look to see which beans aren't on the map).

**Describe the solution you'd like**
I never want to pan & zoom. I'd love a toggle in the settings where I could disable this functionality altogether.

**Describe alternatives you've considered**
Another alternative would be to add some kind of hotkey to automatically reset the map pan & zoom to the default mode. This could (should?) be part of the double click to reset the beans, but it probably wants to be its own button.

It might also be helpful to add a border around the maps canvas. It's kind of hard to drag the map back to the right place because you can't tell when you're about to hit the border.

**Additional context**

**Comment by Kedyn** [comment]
Thank you for your ideas, I think adding a setting to not allow pan or zoom should solve the problem.

**Comment by Anusien** [comment]
I've verified that on the "next" version double clicking the map resets it to the correct place. That's good enough for me.
