### ISSUE TITLE
A way to "Reset Sections" but don't put unused players to Unknown

### ISSUE THREAD

**Issue by Anusien** [Kedyn/fusliez-notes#175]
**Is your feature request related to a problem? Please describe.**
Among Us has 12 colors (pre-June 15th update) but only 10 players. I am frequently moving beans between sections during the game as people die and I form suspicions. But the end of the game is frustrating. The "Reset Sections" button will move the unused beans back to the "Unknown" section. This means I have to manually drag them back out to keep their beans from showing up on the map.
In our games, sometimes we have people rotating in and out. So some of the "Unused" beans have names attached to them. If Player A is Orange and they sit out for a game, I keep their bean named but just move them to "Unusued". But now when I reset the sections, Player A is back in the "Unknown" section. This means I can't just drag the beans without names to "Unused".

**Describe the solution you'd like**
Clicking "Reset Sections" does not move players from any sections defined as "Unused Sections" to the "Reset Section".

**Describe alternatives you've considered**
A secondary alternative would be an extra button called something like "Reset Players". This would reset all the players to the "Reset Section" except the ones in the "Unused Sections".

**Additional context**
If you do this, you may want to tweak the button order. It's probably disruptive to just change it as-is, but if you added a button it would be an opportunity to do this without messing up peoples' muscle memory. My specific concern is that "Reset Sections" (or after this ticket, "Reset Players") is the button you would expect players to hit most often. But the most convenient button is "Reset Scores". I'd think you'd want the buttons to be in order of most often used to least often used left->right and top->bottom.

**Comment by Kedyn** [comment]
Thank you once again for your input, this is somewhat already featured in the upcoming changes: https://kedyn.github.io/fusliez-notes/next/ . When you lock editing, upon hitting the 'Reset Sections' all sections are reset except the unused section. Hitting the 'Reset All' unlocks the editing and all sections. This does not work if 'Show player names' is off because the editing button does not get displayed (just found out right as I write this).

Todo:
- [ ] always show the editing button

**Comment by Anusien** [comment]
I didn't know about /next/. Just verified that lock editing prevents Unused frrom getting reset. That solves my request.

I noticed something weird though. Noting it here, but I'm happy to open a new issue with it:
Beans with names in the "Unused" section sometimes show up on the map:

1. Move a bean with no name from another section to "Unused".
2. The bean disappears (as expected).
3. Add a name to the bean.
4. Double click the map to reset the beans to original positions.
5. The bean doesn't appear but the name is still visible.
In this case, the name can't even be dragged off the map. You have to move them back to another section to remove them from the map.

This also happens if you move a bean with a name from another section to "Unused".
