### ISSUE TITLE
Implement a color change menu for the player images

### ISSUE THREAD

**Issue by kevinydhan** [Kedyn/fusliez-notes#18]
- [ ] When a user clicks on a player image, a menu displaying all available colors should appear above the clicked image.
- [ ] Only one color should be assigned to a player. For the case where a user selects a color that is already taken, the two colors should swap *(tentative?)*.
- [ ] Clicking on the same player image should toggle the menu's display.
- [ ] Clicking on a different player image while the menu is open should reposition the menu above the most recently clicked player image.
- [ ] Selecting a color from the menu should close the menu.
- [ ] Clicking away from the menu when it is open should close the menu.

**Comment by Kedyn** [comment]
I really like this suggestion and think should bump the priority after we fix the restructuring of the project.
