### ISSUE TITLE
Font is hard to read (especially on stream)

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#2]
The typeface with the black weight is very strong and hard to read, in combination with the white text color on the dark grey background.

For the player labels, it's even less readable.

The "Titillium Web" font used in one of the sandbox forks was an improvement.

**Comment by chilblane** [comment]
I think Titillium Web is currently used, but you're only using a 900 weight instead of the 400/500 weights referenced in the CSS.

**Comment by Kedyn** [comment]
Yes, chat asked for a bigger font, I was using 600 so I added the 900... but as previously mentioned I am not good at design, so will trust your judgement :)
