### ISSUE TITLE
Add a linter as a devDependency

### ISSUE THREAD

**Issue by kevinydhan** [Kedyn/fusliez-notes#20]
I would suggest adding `eslint` and `prettier` as linters. If we're using CSS, Sass, or `styled-components`, we can also consider adding `stylelint`.

I added some starting configurations for `eslint` and `prettier`. You can change the configure these files to your liking. You might also want to add additional plugins and configurations for React. 

<br>

**Install command**
```bash
npm install -D @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-prettier eslint-plugin-prettier prettier
```

<br>

`.eslintrc`
```json
{
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint"
  ],
  "parser": "@typescript-eslint/parser"
}
```

<br>

`.prettierrc`

```json
{
  "arrowParens": "always",
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5"
}
```

**Comment by chilblane** [comment]
i would also recommend an editorconfig to match and if you really want, i recommend husky and lint-staged for pre-commit hooks https://codeburst.io/continuous-integration-lint-staged-husky-pre-commit-hook-test-setup-47f8172924fc

**Comment by chilblane** [comment]
also if the project is typescript, should we be using tslint instead?

**Comment by Kedyn** [comment]
Yes! a linter will help us keep all a similar format.

 I think the tslint merged with the eslint.

**Comment by Kedyn** [comment]
I will take a look at the link you just mentioned @chilblane

Also if anyone would like to help with having a direct access to the repo I can add them to the collaborator list.
