### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Cocobo3** [Kedyn/fusliez-notes#202]
When Clicking on the link, https://kedyn.github.io/fusliez-notes/ I'm presented with a blank, white, empty screen. No scroll wheel or options to fix it just sits like this.

Happens every time I click on it, although it works on my phone.

I've been to the site on computer before, I expect it to work properly like on my phone.

**Desktop (please complete the following information):**

- OS: computer 
- Browser chrome
- Version newest

**Comment by Kedyn** [comment]
First of all, happy new year! Sorry, I have not been able to reproduce the issue... maybe try another browser or incognito
