### ISSUE TITLE
Make the color background color for player tiles use some alpha so they're not as strong

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#24]
Current code uses the exact css color name for coloring the background of the tile
```
                  style={{
                    backgroundColor: name
                      ? color === "brown"
                        ? "	saddlebrown"
                        : color
                      : "transparent",
                  }}
```

We should change this so that it uses like x% alpha or something, and blends into the background. Not sure if achievable without restructuring the CSS per #13

**Comment by Kedyn** [comment]
![image](https://user-images.githubusercontent.com/11042906/93012122-6642d200-f552-11ea-80f9-298c19fed8f7.png)
