### ISSUE TITLE
Finalize app design

### ISSUE THREAD

**Issue by kevinydhan** [Kedyn/fusliez-notes#26]
@Kedyn, here is the proposed layout for the app. Let me know what you think!

Also, I think we should decide on whether or not we should keep the interactive map or not.

<br>

![Among Us Notepad](https://user-images.githubusercontent.com/39353049/93413615-a1544680-f86d-11ea-9666-cf027df8658c.png)

**Comment by Kedyn** [comment]
wow, both look good, but yeah doughnut charts seem to have a bit more of an impact when you see them... my vote goes to doughnut charts

**Comment by chilblane** [comment]
the doughnut charts would be much harder to understand quickly, especially at the size they appear on stream

**Comment by kevinydhan** [comment]
> the doughnut charts would be much harder to understand quickly, especially at the size they appear on stream

That's true. Are there any changes I can make to make it work? Or should we stick with the progress bars?

**Comment by chilblane** [comment]
I would stick with the progress bars for that reason + they'd be easier to code and maintain later.

**Comment by kevinydhan** [comment]
Gotcha!

**Comment by chilblane** [comment]
i'm not sure i like the three different progress bars. it's no longer easy to spot what the winning record is. i might try to do some design work of my own to figure it out.

**Comment by kevinydhan** [comment]
No problem, @chilblane. I saw your design on Discord and would be down to implement your design versus mine.

**Comment by chilblane** [comment]
> No problem, @chilblane. I saw your design on Discord and would be down to implement your design versus mine.

Okay, but mine is still pretty rough and still unfinished. I don't like using design tools for interactive prototyping, so I would like to set up a screen share in discord vc to explain how certain aspects of it would work.
