### ISSUE TITLE
Electron app to make a transparent floating mini-version

### ISSUE THREAD

**Issue by genesy** [Kedyn/fusliez-notes#28]
Just an idea when I see game companion apps like this. Better for single monitor users too, haven't played around with electron for a long time now so i'm not sure if they've managed to reduce bundle size.

Also maybe: windows react-native version?

**Comment by Kedyn** [comment]
Creating an electron app, should not be that hard, but we currently do not have good multiple screen size support... which I think should be first before just because most people will just resize the electron window (I think)

**Comment by Kedyn** [comment]
Actually, maybe we should consider this even more, thinking about it could be great not only for single monitor users but for leslie sense she only displays the left side of the app... maybe we can just create a version where is only that part on a window...

**Comment by genesy** [comment]
Haven't cloned/checked the repo out but my initial thought was making it possible in electron to make multiple windows of different components. And let the user move/stick them in positions they want it on.

**Comment by Kedyn** [comment]
I do not about the rest of the team, but I say we need this!

**Comment by genesy** [comment]
Actually made a tool for twitch chat two years ago that did exactly this but with twitch chat. So I have some experience with it. If someone will bootstrap this project with electron i'll contribute :P

**Comment by Kedyn** [comment]
Cool, as soon as I get home I will create a new branch so we can work on this, while others work on the UI on the main branch.

**Comment by genesy** [comment]
I think with this feature we should also be transitioning to redux so the separate windows can share data better. I also suggest implementing redux with redux-toolkit so there's no need to come up with action naming schemes and make it easier to make reducers.

**Comment by Zenoo** [comment]
This would be the only thing I need to be able to use this app, since I only have one monitor when playing.

**Comment by ToxicToast** [comment]
If you actually need people to do that, i have build several apps with electron
