### ISSUE TITLE
Keep separate win rates for crewmate/impostor

### ISSUE THREAD

**Issue by agausmann** [Kedyn/fusliez-notes#3]
With asymmetric games, it can be useful to keep separate stats for different roles. For example in SpyParty Competitive League, they [track stats for Sniper and Spy separately](https://www.spypartyfans.com/playerstats.php?player=krazycaley), because they require different skills to master, just like impostor and crewmate. Separating the win rates like this would be useful to measure performance in each role.

**Comment by Kedyn** [comment]
Yeah that sounds really cool, I actually started watching fuslie because I started watching valkyrea and she current has this, so this would be a great addition.
