### ISSUE TITLE
Feedback/Suggestion Form

### ISSUE THREAD

**Issue by francistse23** [Kedyn/fusliez-notes#30]
Talked to Kedyn and seems like more people/streamers are trying the app out

For users who aren't programmers or don't own GitHub accounts, it might not be as simple as it is for us to contribute to this project

I think a feedback/suggestion form can help centralize the potential improvements we can make to the app

If anyone has used any form library that seems like a good fit for this, please link it. Or if you opt for building our own, I'm down for that as well

Will also need to decide where the suggestions are going (e.g. an email)

**Comment by Kedyn** [comment]
Added a temp solution, might want to add
