### ISSUE TITLE
Change snake_case to camelCase

### ISSUE THREAD

**Issue by kevinydhan** [Kedyn/fusliez-notes#31]
- [ ] Change snake_case to camelCase to maintain consistency with the codebase.
- [ ] Update `.eslintrc` to include a rule to enforce camelCase.

Here are the additions to `.eslintrc`:
```json
{
  ...
  "rules": {
    "camelcase": 1
  }
}
```

**Comment by Kedyn** [comment]
I use snake_case through the project... I feel it makes it easier to distinct from functions, where I use camelCase, PascalCase for classes.

For example:

const use_state = true;
const useState = (value: bollean): void => { console.log("do some state change"); };

but if the majority is on board with me switching from snake_case to camelCase, I am open to do so.

**Comment by kevinydhan** [comment]
> I feel it makes it easier to distinct from functions

I would suggest that we start function names with a verb. This excludes React function components, which I would suggest be in PascalCase.
```typescript
const updateGameScore = (...) => { ... };
const ProgressBar: FunctionComponent<...> = (...) => { ... }; 
```

> PascalCase for classes

I agree that we should stick with PascalCase for classes.

**Comment by francistse23** [comment]
yeah React Component or classes normally uses PascalCase.

functions use camelCase and naming should be an action

and JS's go-to naming convention uses camelCase instead of snake_case
