### ISSUE TITLE
User personas and their priority

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#36]
Since I don't have a better place to put this.

I'd like to put forward some user personas, and decide how important each user is to us, to help us guide priority on feature and release roadmap. After we settle on this, we can add it permanently to the project wiki.

1. Fuslie - She's our guaranteed user, after all. We know that Leslie will use the app as a tool to keep track of her games, which means we should continually make sure it's easy for her to use. We also know that she wants to put the app on the stream scene, so we should be mindful of that (considering what UI components should be shown to viewers or hidden in a second column, etc.)

2. Other streamers - Other streamers, like Cheery for example, have expressed some interest in the tool. We should apply the same considerations for Leslie to these other users, but be mindful we should not personalize the tool too much to Leslie by default.

3. General desktop users - Users playing Among Us without streaming the game. I'd like to know more about these users: are they playing with multiple displays? Are they satisfied with using the tool in the browser app or would be a standard program be enough of a benefit?

4. General mobile users - These users will play Among Us using their phone (or tablet?) as a second screen. I would like to know how common this practice would be. Creating a good experience for a small touch-based screen is a challenge.

**Comment by Kedyn** [comment]
1. I agree with all of this, I think we can also just remove the "title", to make it a bit more marketable.

2. As of right now most data is saved, so this means we could create a setup for first time users or just don't think this as an issue, you will only need to edit once and your data will be saved.

3. As mentioned on @francistse23's PR,  I think we can just make a mini version with just the main column of the project.

4. I think we could remove the "use player names" to make icons bigger, I did not see many mobile comments... also analytics show 23% of users to use mobile... so this could be pushed back, but I think having mobile friendly app is always good.

**Comment by chilblane** [comment]
I currently have three biggish features in my head: imposter/crewmate mode for player tiles, standalone desktop app, and mobile friendly layout. Am I missing anything?

**Comment by francistse23** [comment]
just sharing my opinions. I am very new at contributing to open source app/code base. I appreciate any suggestion/improvement and would definitely love to learn about new/better ways to do things as I have been collaborating with the team so far.

love that we are going for some sort of road map. that will make each version upgrade clearer and what we need to work on.

1. Fuslie - I personally was thinking of building this app around Leslie. Like you said, we know that she has been utilizing the app during gameplays. I mentioned to Kedyn (SykO) about getting Leslie a little bit involved in this. I am sure the team would love to hear if there are some features that she wants, but the team and the other users have not mentioned. I think she's only showing the leftmost column (MainContent) on stream via OBS. Depending on how many people actually uses the MainContent column only, we can create a version with just that (removing notes and maps).

2 - Other Streamers - Definitely can make it more generic by changing the title to Among Us Notes (like chilblane has it in his Figma design) or still keep a reference of Leslie in the work somehow. She was the inspiration/motivation behind this project after all. In terms of player data, we can remove the Leslie's default orange avatar and just leave it blank.

3 - General desktop users - We can perhaps get a feel of how many users own multiple displays and uses them for the notes. I think a lot of them are thinking of it as an overlay like the Discord bubbles so they don't have to Alt+Tab out of the game to make updates. That's a really nice to have and that might take some time to implement. I don't think the core team has much experience in developing in Electron and create anything like that, although I'd like to experiment with it and it'll be really awesome if we can get that to work.

4 - General mobile users - If the feedback returns that many users say that they only have 1 screen, say they are playing on a laptop or something, chances are they might be using their phone to run the app. In that case, I would like to push for the mobile layout as that would give them another option to use the app. While most people would like to see it on mobile, or at least usable, it is easy to vote Yes/No on the feedback form and generate a lot of work for the team. With that said, I don't mind implementing a version of it and see if that solves most users' problems.

Honestly speaking... I would like to see this app take off, but I don't want to invest more time in it than necessary. While the streamer groups are still playing Among Us frequently, I can see the popularity die off and whatever work and effort we are putting in might not be worth it.

**Comment by francistse23** [comment]
> I currently have three biggish features in my head: imposter/crewmate mode for player tiles, standalone desktop app, and mobile friendly layout. Am I missing anything?

I think that's it? For me I would like to see how can we condense some of the buttons/settings so the UI is less cluttered/minimalistic

**Comment by DavidVu96** [comment]
One comment about mobile user is the game will disconnect them if you switch away from the game (e.g. switch to a messenger app). So it's very hard or impossible on iOS, while we can try some facebook chat-head pop up equivalent for Android.
