### ISSUE TITLE
Support for other language

### ISSUE THREAD

**Issue by federamadan** [Kedyn/fusliez-notes#37]
Hi, im using this app and find it very usefull, specially because im new to the game and dont know the maps and that stuff.. But i play the game in Spanish with my friends, so i wanted to know if could be posible to add a second lenguage, at least for the map locations.  If not, then i would like to know how to use the code to change the text strings by myself, but im not very good at coding.
Thank you very much :)

**Comment by Kedyn** [comment]
I did thought of this a few days ago, but the only problem with what you are saying is about the map locations and that is just an image... so there is nothing I can do about that.. if you find the images in Spanish, please do share.

**Comment by francistse23** [comment]
probably just takes someone with some photoshop skills and knows Spanish (or other languages)

**Comment by federamadan** [comment]
Yeah, i thought the same.. If the map is just an image, then there is no text to edit.. I will see if i can get a good picture, or edit the English version..

**Comment by federamadan** [comment]
Here are the screenshots of the maps with the spanish locations.. Just in case someone with good skills in PS want to edit it, i will try it by myself, though.. My idea is to keep the same map style, with the vents connections, camera zones, etc.
<details>
 <summary>Mira map</summary>
 
![Mira](https://user-images.githubusercontent.com/44484938/93690309-2da07c80-faad-11ea-8446-a554d3faa71b.png)
</details>

<details>
 <summary>Polus map</summary>

![Polus](https://user-images.githubusercontent.com/44484938/93690371-de0e8080-faad-11ea-9197-c7920fd4ff73.png)
</details>

<details>
 <summary>Skeld map</summary>

![Skeld](https://user-images.githubusercontent.com/44484938/93690400-46f5f880-faae-11ea-8284-6f4561030045.png)
</details>

**Comment by Kedyn** [comment]
Would like the image to be the same, I might create an svg so we can just add the text for any language, but this is in my low priority list.

**Comment by Kinishina** [comment]
Hey. I had a few spare minutes. Here you go:
- For everyone to translate: [Among Us no-text maps.zip](https://github.com/Kedyn/fusliez-notes/files/5262244/Among.Us.no-text.maps.zip)
- Russian maps translation by me, using in-game info: [Among Us RU translation maps.zip](https://github.com/Kedyn/fusliez-notes/files/5262252/Among.Us.RU.translation.maps.zip)
- Text file with UI translation for everything on the page right now: [Russian translation for fusliez-notes.txt](https://github.com/Kedyn/fusliez-notes/files/5262261/Russian.translation.for.fusliez-notes.txt)

People can yell at my twitter @KinishinaTwitch if there are any mistakes in RU translation. Feel free to ping me, if you need to translate something additional on the site. Maps are PNG, not SVG, so you still could improve quality later. I just don't have time to re-draw everything from scratch.

**Comment by Kedyn** [comment]
@Kinishina amazing work, with the no-text version should work for us to just add text on top of the image, hope we can count on you to help us with the Russian translations once we add translations. Thank you.

**Comment by Kinishina** [comment]
Yeah, no problem, I will help. I see notifications from github or you can text me on twitter, either works.

**Comment by Kedyn** [comment]
@federamadan @Kinishina  I have added support to add languages as you can see: https://github.com/Kedyn/fusliez-notes/tree/master/src/assets/locales

Note: we have not completed all the features that will need translation, but the most important visible parts are already there, if you do not know how to add your translations just hit post your translation.json file here and i will gladly add it.

**Comment by Kinishina** [comment]
@Kedyn I'm sorry, but I don't understand what you need right now. Do you have example file somewhere? I couldn't find anything that includes lines of text which I need to translate. I can make a list myself, but I'm guessing that's not what you want. 
I can add translations as you go, that's not an issue. I will warn in advance if it won't be posible for me anymore. But, please, firstly, explain what you need or make a file with text which I need to translate.

**Comment by Kedyn** [comment]
@Kinishina sorry we had to change some stuff around the repo, here is the new link: https://github.com/Kedyn/fusliez-notes/tree/language/src/assets/locales

as you can see we have 2 folder `en-US` and `es-MX`, both containing a file called `translation.json`. The `es-MX` only contains translation for the settings, as of right now.

**Comment by Kinishina** [comment]
That makes sense now! I see what you mean, will do sometime tomorrow. Probably will drop it here, as I'm not actually familiar with anything outside of comments on Github yet :D

**Comment by Kedyn** [comment]
Amazing, thanks for your help.

**Comment by Kinishina** [comment]
Here, json with Russian [ru-RU.zip](https://github.com/Kedyn/fusliez-notes/files/5286924/ru-RU.zip)

**Comment by Kedyn** [comment]
Thank you for catching that, I have added it to the translation file.

**Comment by Kedyn** [comment]
@Kinishina I have added a bit more things for this version, I believe no new changes will be made.

https://github.com/Kedyn/fusliez-notes/blob/master/src/assets/locales/ru-RU/translation.json

The additions are still in English.

Also, would like to know your name to put it on the About modal, you can see it here: https://kedyn.github.io/fusliez-notes/next/ by clicking the fusfam link at the bottom of the page. If your okay with how I have added your github info, then you do not have to give me your name. Once again, thank you for doing this.

**Comment by Kinishina** [comment]
@Kedyn I updated RU translation.
> Also, would like to know your name to put it on the About modal

Just Kinishina is fine, thank you.

I want to suggest you to re-name some of the settings, specifically:
- "Neutral/Innocent/Impostor Text Color" changing secondary circle/bar color, not a text;
- Why "Neutral" when it's "Total"/"Overall" score?;
- I feel like you may wanna add "Neutral/Innocent/Impostor **score** Background Color" something like this for clarity;
- "Button Danger" almost untranslatable and don't make a lot of sense even in English as it include button "Settings". Something like "Important"/"Major"? I dunno. "First button color"/"Second button color" :D

Also, technically, you skipped "On"/"Off" in translation list, but they are pretty much known by everyone. You can decide if you wanna translate them too.

**Comment by Kedyn** [comment]
sorry I was not really thinking about how much sense it made. I do like your suggestions and I will be changing it on the next version, plus chilblane seems to be changing multiple UI things, so I will be revisiting the settings.

As for the on and off, it was a mess aligning it and if we change it, it might get all messed up again and as you say, it is commonly known. Therefore, I think I will just leave it as on and off.

Do not worry, our next version is also setting those in the center so it will not look like in the picture.
