### ISSUE TITLE
Various dark mode/light mode contrast and color fixes

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#5]
- [ ] Notes textarea background color in dark mode should use a dark background
- [ ] "Winning rate" text should be white regardless of theme
- [ ] Win rate progress bar should use a muted or semi-opaque shade of red so it clashes less with the green (see my fork for example: https://9ejrq.csb.app/). Or, somehow a divider should be added between the green and red area (might be difficult with Bootstrap Progress component)

**Comment by Kedyn** [comment]
Maybe we might just want to move away from bootstrap, the amount of controls and styles are not that many.

We could also use something like jss to make styling each component easier and have a little better structure.

For example, each component would follow the following structure:

```
./ComponentName/
  ComponentName.styles.ts
  ComponentName.tsx
  index.ts
```

There is a VSCode extension that generates this files called **VSCode React Component Generator**.

I also have a few snippets I could put in the repo so we can all follow the same format.

Will open another issue where we could discuss the project structure and this can just remain about the issue at hand.

**Comment by Kedyn** [comment]
I do not think this will be done by today so moving it to the next version
