### ISSUE TITLE
Hide unused colors from map

### ISSUE THREAD

**Issue by francistse23** [Kedyn/fusliez-notes#53]
a response on feedback asking us to remove unused/dead players from the map (same person, but he made the comment twice):

>  Can you make it so that if a color is NOT given a name OR dead, please make that color unavailable on the map. This way, we can focus on the remaining colors!

makes sense to me and I don't mind putting that in.

implementation shouldnt be too difficult. we can add in the next patch if everyone is on board

**Comment by Kedyn** [comment]
This feels like is just too much, I think this should just be a tool to help you learn the game (at least for the map) and not to just straight up help you win the game. Therefore I do not feel okay with adding more to it (the map).
