### ISSUE TITLE
Is there a reason why we don't have the southeast direction in the direction.json files?

### ISSUE THREAD

**Issue by danilolmoura** [Kedyn/fusliez-notes#54]
I'm doing the translation to pt-BR and I realized that between the [directions,](https://github.com/Kedyn/fusliez-notes/blob/master/src/assets/locales/en-US/translation.json#L58-L63) we don't have the southeast direction

Is there some reason? Can I add it?

**Comment by Kedyn** [comment]
As you can see, only the maps, only Polus contains names for the cameras. It does not contain the southeast direct.

**Comment by danilolmoura** [comment]
I got it, thanks!
