### ISSUE TITLE
Add missing metadata

### ISSUE THREAD

**Issue by chilblane** [Kedyn/fusliez-notes#57]
- [ ] Find a better favicon

- [x] Add the missing open graph / social metadata and any mobile icon files

**Comment by chilblane** [comment]
updating the favicon will be done by @kevinydhan separately

**Comment by Kedyn** [comment]
This is the icon I came up with

![fusNotes](https://user-images.githubusercontent.com/11042906/98430226-fdaf3780-2060-11eb-9d93-f8bb5bf4892a.png)


Idk, might use it if no one else comes up with a better one...

**Comment by chilblane** [comment]
That's not going to look good at 16x16. You need something simple.

**Comment by Unviray** [comment]
![amongusNote](https://user-images.githubusercontent.com/44167149/100702896-68bb0800-339a-11eb-95d5-7a5c2bb4dfc6.png)

**Comment by gdomingu** [comment]
![dum](https://user-images.githubusercontent.com/4443635/102743148-b5e02900-430b-11eb-8e0f-1f07f844d52c.png)
