### ISSUE TITLE
Feature request: Add pagination to map tool for tracking player positions per-round

### ISSUE THREAD

**Issue by thekevincurtin** [Kedyn/fusliez-notes#59]
It would be nice to save the locations of players per round, I often forget what players were grouped with me on past rounds

**Comment by francistse23** [comment]
hey there, thank you for your suggestion.

I've talked to other developers and maintainers of this project and decide to not implement this feature (or any other similar ones, e.g. players' pathing)

we appreciate the suggestion regardless. let us know if you can think of other possible improvements to our app. thanks!
