### ISSUE TITLE
Translations update for v0.10.0

### ISSUE THREAD

**Issue by Kedyn** [Kedyn/fusliez-notes#66]
We have finished our changes to the UI for the next release, so to anyone willing to update their translations please do so

- [ ] Russian (@Kinishina)
- [x] Portuguese (@danilolmoura)
- [x] German (@Fabian9799)
- [x] Spanish

Files:
https://github.com/Kedyn/fusliez-notes/tree/master/src/assets/locales

**Comment by francistse23** [comment]
is German up to date?

**Comment by Kedyn** [comment]
Yes, German was added today.

**Comment by danilolmoura** [comment]
I'll take the portuguese translation, ok?

**Comment by Kedyn** [comment]
Added settings.useColorBlindMode to translations

**Comment by Kedyn** [comment]
New issue will be open for the next version as soon as all UI additions/changes are completed.
