### ISSUE TITLE
Close button X Off-Centered

### ISSUE THREAD

**Issue by francistse23** [Kedyn/fusliez-notes#68]
The "X" in the close button is off-centered

**Comment by chilblane** [comment]
appears to be an issue with specificity: the button styles are lower in the dom than the closebutton

**Comment by francistse23** [comment]
I attempted to fix it by removing the spread operator on props in `CloseButton`, `{...others}` to be specific. 

reloaded the page and the issue was gone. class names were still in the `Button` then `CloseButton` order (`class="Button-0-2-82 CloseButton-0-2-137"`).  not entirely sure if that addressed the issue

**Comment by chilblane** [comment]
I can't repro that solution, it's still broken for me.
