### ISSUE TITLE
Save session configuration data

### ISSUE THREAD

**Issue by Kedyn** [Kedyn/fusliez-notes#8]
Save data such as score, theme mode, notes maybe?

- [x] score
- [x] theme
- [x] notes ?
- [x] player names ?

**Comment by francistse23** [comment]
if you're cool with using local storage, I can throw something together

**Comment by Kedyn** [comment]
Yeah that is what i was thinking...

Also thinking maybe to use react-redux to make shareable data "easier".

**Comment by francistse23** [comment]
either that, or hoist all data to App, use useReducer to manage the data, and maybe the Context API to consume it so we don't have to prop drill

**Comment by Kedyn** [comment]
Will be honest, I have not used the Context API, but it sounds better for a somewhat small project.
And hopefully this can help me get to use it.

**Comment by francistse23** [comment]
yeah redux requires a whole setup. way easier to use with hooks now, but still a pain to deal with
