### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by francistse23** [Kedyn/fusliez-notes#81]
Will be adding tests to app using `react-testing-library`

**Comment by Kedyn** [comment]
any updates on this?

**Comment by francistse23** [comment]
still working on it. not the easiest thing.

dont expect super elaborate test on the first push, trying to get something bare minimum going before we do that

**Comment by francistse23** [comment]
i dont think this is crucial to 1.0 release. 

i know we wanted to, but i believe this can wait if you want to push the other updates through
