### ISSUE TITLE
State Not Preserved on Refresh

### ISSUE THREAD

**Issue by francistse23** [Kedyn/fusliez-notes#91]
From feedback:
> Should add option for cookies to save your information so you don't lose it every time you refresh

I did a quick test and noticed only notes are saved, but not players, scores, etc. 

If this was intended in any way, please close the issue

**Comment by Kedyn** [comment]
This was intended as I noticed, at least from fuslie's stream and the few games I played, that the players change constantly therefore I did not see the need to save said information. We could always add this to be an option.

**Comment by francistse23** [comment]
I always think there could some accidental refresh/close tab happening. 

That's why I wanted to preserve the state in some way in case that happens

**Comment by Kedyn** [comment]
I feel that those can be easily replaced/added back, unlike the notes. Therefore I did not see the need for them, but once again I am open to adding an option to save session data, including players names and scores.

**Comment by francistse23** [comment]
in my opinion, saving the data should be the default

if there needs to be a mass reset, that's what the `Reset All` button is for

I'll let you decide what direction you want to go with for this

**Comment by kognise** [comment]
Alright with y'all if I try a simple localstorage-based implementation of this?

**Comment by francistse23** [comment]
we had something implemented before we converted our state store to redux. kedyn can decide whether to use local storage/other  storing methods or leave it as is

**Comment by Kedyn** [comment]
@kognise all contributions are welcome.

As @francistse23 mentioned, we did have this implemented in the past, I decided to take it off. But I do believe @francistse23 statement about the reset button, therefore I did have plans to reimplement this as a middleware for the store.
